"""empty message

Revision ID: 663c2c8c229f
Revises: 67296f29cca8
Create Date: 2025-08-14 01:29:46.623641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663c2c8c229f'
down_revision = '67296f29cca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
