"""empty message

Revision ID: 67296f29cca8
Revises: ea1bb58276f9
Create Date: 2025-08-14 00:28:16.768586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67296f29cca8'
down_revision = 'ea1bb58276f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_environments_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_foreign_key(None, 'clusters', ['cluster_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_environments_cluster_id'))
        batch_op.drop_column('cluster_id')

    # ### end Alembic commands ###
