"""empty message

Revision ID: 8848fb491bda
Revises: d9138f5c4981
Create Date: 2025-08-27 00:04:56.823163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8848fb491bda'
down_revision = 'd9138f5c4981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_info', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_column('access_info')

    # ### end Alembic commands ###
