"""empty message

Revision ID: b23cde15b056
Revises: 663c2c8c229f
Create Date: 2025-08-14 01:46:55.639622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cde15b056'
down_revision = '663c2c8c229f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_environments_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_environments_environment_id'), ['environment_id'], unique=False)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_cluster_id'))
        batch_op.drop_constraint(batch_op.f('environments_cluster_id_fkey'), type_='foreignkey')
        batch_op.drop_column('cluster_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('environments_cluster_id_fkey'), 'clusters', ['cluster_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_environments_cluster_id'), ['cluster_id'], unique=False)

    with op.batch_alter_table('cluster_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_environments_environment_id'))
        batch_op.drop_index(batch_op.f('ix_cluster_environments_cluster_id'))

    op.drop_table('cluster_environments')
    # ### end Alembic commands ###
