"""init models

Revision ID: ba88b3c77517
Revises: 
Create Date: 2025-08-13 23:45:27.000065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba88b3c77517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_name'), ['name'], unique=True)

    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_name'), ['name'], unique=False)

    op.create_table('docker_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docker_environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docker_environments_image'), ['image'], unique=False)

    op.create_table('vm_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_path', sa.String(length=512), nullable=False),
    sa.Column('base_image_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_environments')
    with op.batch_alter_table('docker_environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docker_environments_image'))

    op.drop_table('docker_environments')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_name'))

    op.drop_table('environments')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_name'))

    op.drop_table('clusters')
    # ### end Alembic commands ###
