"""empty message

Revision ID: d9138f5c4981
Revises: b23cde15b056
Create Date: 2025-08-16 02:46:27.668562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9138f5c4981'
down_revision = 'b23cde15b056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template', sa.JSON(), nullable=False))
        batch_op.drop_column('template_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.drop_column('template')

    # ### end Alembic commands ###
